# Auto-generated by 4B.4.3.6.6.25AE-H1
# HYP-005-R1 eight-symbol fresh-ledger no-order shadow cycle.
# Safety: no training, reload, paper trade, live trade, POST request, or order action.

$ErrorActionPreference = "Stop"
$PackDir = $PSScriptRoot
$ReportsDir = Split-Path -Parent $PackDir
$ProjectRoot = Split-Path -Parent $ReportsDir
if (-not (Test-Path (Join-Path $ProjectRoot "tools"))) {
  $ProjectRoot = Split-Path -Parent $PackDir
}
Set-Location $ProjectRoot

$env:PYTHONPATH = "src"
$env:PYTEST_DISABLE_PLUGIN_AUTOLOAD = "1"
$R1ReportsDir = Join-Path $ProjectRoot "reports\hyp005_r1"
$CandidateSpec = Join-Path $PackDir "hyp005_r1_runtime_candidate_spec.json"
New-Item -ItemType Directory -Force -Path $R1ReportsDir | Out-Null

Write-Host "[HYP-005-R1] Starting eight-symbol fresh-ledger no-order shadow cycle..."
Write-Host "[HYP-005-R1] Fresh namespace: HYP005_R1"
Write-Host "[HYP-005-R1] Reports dir: $R1ReportsDir"

python tools/run_hyp005_shadow_observation_logger_4B436625V.py `
  --candidate-spec-json "$CandidateSpec" `
  --symbols "ADAUSDT,BNBUSDT,BTCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,SOLUSDT,XRPUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "$R1ReportsDir" `
  --review-ok

python tools/run_hyp005_shadow_collection_orchestrator_4B436625X.py `
  --candidate-spec-json "$CandidateSpec" `
  --reports-dir "$R1ReportsDir" `
  --include-all `
  --symbols "ADAUSDT,BNBUSDT,BTCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,SOLUSDT,XRPUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "$R1ReportsDir" `
  --review-ok

python tools/run_hyp005_shadow_acceptance_readiness_4B436625W.py `
  --reports-dir "$R1ReportsDir" `
  --include-all `
  --out-dir "$R1ReportsDir" `
  --review-ok

python tools/run_hyp005_shadow_operator_runbook_4B436625Y.py `
  --candidate-spec-json "$CandidateSpec" `
  --reports-dir "$R1ReportsDir" `
  --include-all `
  --symbols "ADAUSDT,BNBUSDT,BTCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,SOLUSDT,XRPUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "$R1ReportsDir" `
  --review-ok

Write-Host "[HYP-005-R1] Cycle completed. Fresh-ledger namespace isolated. Paper/live/order remain disabled."
