# Auto-generated by 4B.4.3.6.6.25AE-H3
# HYP-005-R1 eight-symbol isolated fresh-ledger no-order shadow cycle.
# Safety: no training, reload, paper trade, live trade, POST request, or order action.

$ErrorActionPreference = "Stop"
$PackDir = $PSScriptRoot
$ReportsDir = Split-Path -Parent $PackDir
$ProjectRoot = Split-Path -Parent $ReportsDir
if (-not (Test-Path (Join-Path $ProjectRoot "tools"))) {
  $ProjectRoot = Split-Path -Parent $PackDir
}
Set-Location $ProjectRoot

$env:PYTHONPATH = "src"
$env:PYTEST_DISABLE_PLUGIN_AUTOLOAD = "1"
$ProjectRoot = [System.IO.Path]::GetFullPath($ProjectRoot)
$R1ReportsDir = [System.IO.Path]::GetFullPath((Join-Path $ProjectRoot "reports\hyp005_r1_isolated"))
$ExpectedR1ReportsDir = [System.IO.Path]::GetFullPath((Join-Path $ProjectRoot "reports\hyp005_r1_isolated"))
$CandidateSpec = Join-Path $PackDir "hyp005_r1_runtime_candidate_spec.json"

if ($R1ReportsDir -ne $ExpectedR1ReportsDir) {
  throw "HYP-005-R1 reports-dir isolation violation. Expected: $ExpectedR1ReportsDir Actual: $R1ReportsDir"
}
if ($R1ReportsDir -eq [System.IO.Path]::GetFullPath((Join-Path $ProjectRoot "reports"))) {
  throw "HYP-005-R1 reports-dir isolation violation: project reports root is forbidden."
}
New-Item -ItemType Directory -Force -Path $R1ReportsDir | Out-Null

Write-Host "[HYP-005-R1] Starting isolated eight-symbol fresh-ledger no-order shadow cycle..."
Write-Host "[HYP-005-R1] Fresh namespace: HYP005_R1"
Write-Host "[HYP-005-R1] Isolated reports dir: $R1ReportsDir"

python tools/run_hyp005_shadow_observation_logger_4B436625V.py `
  --candidate-spec-json "$CandidateSpec" `
  --symbols "ADAUSDT,BNBUSDT,BTCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,SOLUSDT,XRPUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "$R1ReportsDir" `
  --review-ok

$LatestLoggerReport = Get-ChildItem -File -Path (Join-Path $R1ReportsDir "4B436625V_hyp005_shadow_observation_logger_*.json") |
  Sort-Object LastWriteTime -Descending | Select-Object -First 1
$LatestLoggerLedger = Get-ChildItem -File -Path (Join-Path $R1ReportsDir "4B436625V_hyp005_shadow_observation_ledger_*.json") |
  Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $LatestLoggerReport -or -not $LatestLoggerLedger) {
  throw "HYP-005-R1 isolated logger report/ledger not found."
}

python tools/run_hyp005_shadow_collection_orchestrator_4B436625X.py `
  --candidate-spec-json "$CandidateSpec" `
  --logger-report-json "$($LatestLoggerReport.FullName)" `
  --ledger-json "$($LatestLoggerLedger.FullName)" `
  --reports-dir "$R1ReportsDir" `
  --strict-explicit-chain `
  --symbols "ADAUSDT,BNBUSDT,BTCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,SOLUSDT,XRPUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "$R1ReportsDir" `
  --review-ok

$LatestCollectionReport = Get-ChildItem -File -Path (Join-Path $R1ReportsDir "4B436625X_hyp005_shadow_collection_orchestrator_*.json") |
  Sort-Object LastWriteTime -Descending | Select-Object -First 1
$LatestMergedLedger = Get-ChildItem -File -Path (Join-Path $R1ReportsDir "4B436625X_hyp005_shadow_merged_ledger_*.json") |
  Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $LatestCollectionReport -or -not $LatestMergedLedger) {
  throw "HYP-005-R1 isolated collection report/merged ledger not found."
}

python tools/run_hyp005_shadow_acceptance_readiness_4B436625W.py `
  --collection-report-json "$($LatestCollectionReport.FullName)" `
  --ledger-json "$($LatestMergedLedger.FullName)" `
  --reports-dir "$R1ReportsDir" `
  --strict-explicit-chain `
  --out-dir "$R1ReportsDir" `
  --review-ok

$LatestAcceptanceReport = Get-ChildItem -File -Path (Join-Path $R1ReportsDir "4B436625W_hyp005_shadow_observation_acceptance_*.json") |
  Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $LatestAcceptanceReport) { throw "HYP-005-R1 isolated acceptance report not found." }

python tools/run_hyp005_shadow_operator_runbook_4B436625Y.py `
  --candidate-spec-json "$CandidateSpec" `
  --logger-report-json "$($LatestLoggerReport.FullName)" `
  --collection-report-json "$($LatestCollectionReport.FullName)" `
  --acceptance-report-json "$($LatestAcceptanceReport.FullName)" `
  --ledger-json "$($LatestMergedLedger.FullName)" `
  --reports-dir "$R1ReportsDir" `
  --strict-explicit-chain `
  --symbols "ADAUSDT,BNBUSDT,BTCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,SOLUSDT,XRPUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "$R1ReportsDir" `
  --review-ok

Write-Host "[HYP-005-R1] Cycle completed. R1 reports-dir isolated; baseline reports root was not read. Paper/live/order remain disabled."
