# Auto-generated by 4B.4.3.6.6.25Z
# Manual registration helper for Windows Task Scheduler.
# It registers only the no-order shadow collection cycle script.
# Review before running. This script still does not enable paper/live trading.

$ErrorActionPreference = "Stop"
$PackDir = $PSScriptRoot
$ProjectRoot = Split-Path -Parent $PackDir
$TaskName = "TradeBot_HYP005_NoOrderShadowCollection"
$CycleScript = Join-Path $PackDir "run_hyp005_shadow_cycle_no_order.ps1"

$Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$CycleScript`""
$Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddHours(4) -RepetitionInterval (New-TimeSpan -Hours 4) -RepetitionDuration (New-TimeSpan -Days 3650)
$Settings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -StartWhenAvailable -AllowStartIfOnBatteries:$false -DisallowStartIfOnBatteries:$true

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Description "HYP-005 no-order shadow collection cycle. No paper/live/order actions." -Force

Write-Host "Registered task: $TaskName"
Write-Host "Cycle script: $CycleScript"
Write-Host "Safety: no paper/live/order actions are enabled by this task."
