# Auto-generated by 4B.4.3.6.6.25AE-H2
# Manual operator-reviewed Windows Task Scheduler registration helper.
# Safety: baseline task and any existing R1 task must be Disabled before replacement.

$ErrorActionPreference = "Stop"
$PackDir = $PSScriptRoot
$BaselineTaskName = "TradeBot_HYP005_NoOrderShadowCollection"
$TaskName = "TradeBot_HYP005_R1_NoOrderShadowCollection"
$CycleScript = Join-Path $PackDir "run_hyp005_r1_shadow_cycle_no_order.ps1"

$BaselineTask = Get-ScheduledTask -TaskName $BaselineTaskName -ErrorAction Stop
if ($BaselineTask.State -ne "Disabled") {
  throw "Baseline task '$BaselineTaskName' must be Disabled before HYP-005-R1 registration. Current state: $($BaselineTask.State)"
}
$ExistingR1Task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($null -ne $ExistingR1Task -and $ExistingR1Task.State -ne "Disabled") {
  throw "Existing R1 task '$TaskName' must be Disabled before H2 replacement. Current state: $($ExistingR1Task.State)"
}

$Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$CycleScript`""
$Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddHours(4) -RepetitionInterval (New-TimeSpan -Hours 4) -RepetitionDuration (New-TimeSpan -Days 3650)
$Settings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -StartWhenAvailable
$SettingPropertyNames = @($Settings.PSObject.Properties.Name)
if ($SettingPropertyNames -contains "DisallowStartIfOnBatteries") { $Settings.DisallowStartIfOnBatteries = $true }
if ($SettingPropertyNames -contains "StopIfGoingOnBatteries") { $Settings.StopIfGoingOnBatteries = $true }
if ($SettingPropertyNames -contains "AllowStartIfOnBatteries") { $Settings.AllowStartIfOnBatteries = $false }

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Description "HYP-005-R1 isolated fresh-ledger no-order shadow collection cycle. No paper/live/order actions." -Force

Write-Host "Registered task: $TaskName"
Write-Host "Baseline task confirmed Disabled: $BaselineTaskName"
Write-Host "Existing R1 task disable/replacement guard: PASS"
Write-Host "Cycle script: $CycleScript"
Write-Host "Safety: HYP005_R1 isolated fresh ledger only; no paper/live/order actions are enabled."
