const state = { snapshot: null, health: null, events: [] };
const TOKEN_KEY = 'tradebot.cleanDashboard.authToken';
const OPERATOR_KEY = 'tradebot.cleanDashboard.operatorId';
const $ = (id) => document.getElementById(id);
const text = (id, value) => { const el = $(id); if (el) el.textContent = value ?? '-'; };
const bool = (value) => value === true ? 'yes' : value === false ? 'no' : '-';
const num = (value, digits = 4) => Number.isFinite(Number(value)) ? Number(value).toFixed(digits) : '-';

function setConnection(label, ok = false) { const badge = $('connectionBadge'); if (badge) { badge.textContent = label; badge.className = `badge ${ok ? 'badge-ok' : 'badge-warn'}`; } }
function authHeaders() { const headers = { 'Accept': 'application/json' }; const token = localStorage.getItem(TOKEN_KEY) || ''; const operator = localStorage.getItem(OPERATOR_KEY) || ''; if (token) headers['X-TradeBot-Auth'] = token; if (operator) headers['X-TradeBot-Operator'] = operator; return headers; }
function loadSecurityInputs() { const operator = localStorage.getItem(OPERATOR_KEY) || 'operator-local'; const token = localStorage.getItem(TOKEN_KEY) || ''; if ($('operatorInput')) $('operatorInput').value = operator; if ($('tokenInput')) $('tokenInput').value = token; }
function saveSecurityInputs() { localStorage.setItem(OPERATOR_KEY, $('operatorInput')?.value?.trim() || 'operator-local'); localStorage.setItem(TOKEN_KEY, $('tokenInput')?.value || ''); refreshDashboard(); }
async function getJson(path) { const response = await fetch(path, { headers: authHeaders() }); if (!response.ok) throw new Error(`${path} -> HTTP ${response.status}`); return response.json(); }
function runtimeFromSnapshot(snapshot) { return snapshot?.runtime || snapshot?.engine_status || snapshot?.status || snapshot || {}; }
function renderRisk(snapshot) { const awareness = snapshot?.runtime_awareness || snapshot?.awareness || {}; const badge = String(awareness.risk_badge || snapshot?.risk_badge || 'UNKNOWN').toUpperCase(); text('riskTitle', awareness.banner_title || 'Runtime inventory tracking'); text('riskMessage', awareness.banner_message || awareness.message || 'No active risk message.'); text('riskBadge', badge); const risk = $('riskBadge'); if (risk) risk.className = `risk-badge risk-${badge === 'RED' ? 'red' : badge === 'YELLOW' ? 'yellow' : badge === 'GREEN' ? 'green' : 'yellow'}`; }
function renderMetrics(snapshot, health) { const runtime = runtimeFromSnapshot(snapshot); const signal = snapshot?.signal || runtime?.signal || {}; const position = snapshot?.position || runtime?.position || {}; const security = health?.security || snapshot?.security || snapshot?.request_security || {}; text('contractVersion', `contract: ${health?.contract_version || snapshot?.contract_version || '-'}`); text('runtimeState', runtime.state || runtime.runtime_state || '-'); text('symbol', runtime.symbol || snapshot?.symbol || '-'); text('wsStatus', runtime.ws_status || runtime.websocket_status || '-'); text('signal', signal.signal || runtime.last_signal || '-'); text('provider', signal.provider || runtime.last_signal_provider || '-'); text('confidence', num(signal.confidence ?? runtime.last_signal_confidence)); text('positionStatus', position.side || position.status || runtime.position_side || '-'); text('positionQty', num(position.qty ?? position.quantity ?? runtime.position_qty)); text('unrealizedPnl', num(position.unrealized_pnl ?? runtime.unrealized_pnl)); text('authRequired', bool(security.auth_required)); text('operatorRequired', bool(security.operator_required)); text('failClosed', bool(security.fail_closed_no_token)); }
function renderList(containerId, rows) { const box = $(containerId); if (!box) return; box.replaceChildren(); rows.forEach(([label, value]) => { const row = document.createElement('div'); const labelEl = document.createElement('span'); const valueEl = document.createElement('strong'); row.className = 'status-item'; labelEl.textContent = label; valueEl.textContent = value ?? '-'; row.append(labelEl, valueEl); box.appendChild(row); }); }
function renderGuardrails(snapshot) { const lock = snapshot?.runtime_lock || {}; const reconciliation = snapshot?.risk_reconciliation || {}; const entry = snapshot?.entry_guard || {}; renderList('guardrailList', [['Runtime lock', lock.locked ?? lock.status ?? '-'], ['Stale reclaim safe', bool(lock.stale_reclaim_safe)], ['Reconciliation', reconciliation.status || reconciliation.reason_code || '-'], ['Entry disabled', bool(entry.force_buy_disabled)], ['Entry reason', entry.disable_reason || '-']]); }
function renderModel(snapshot) { const model = snapshot?.model || snapshot?.ai || snapshot?.ai_provider || {}; const runtime = runtimeFromSnapshot(snapshot); const metrics = runtime.last_signal_metrics || {}; renderList('modelList', [['Provider', model.provider || runtime.last_signal_provider || '-'], ['Available', bool(model.available)], ['Schema', model.schema_version || metrics.schemaVersion || '-'], ['Feature count', model.feature_count ?? metrics.featureCount ?? '-'], ['Fallback mode', metrics.aiFallbackMode || '-']]); }
function renderEvents(events) { const box = $('eventLog'); if (!box) return; box.replaceChildren(); (events || []).slice(0, 80).forEach((event) => { const row = document.createElement('div'); const level = document.createElement('span'); const code = document.createElement('strong'); const message = document.createElement('span'); row.className = 'event-row'; level.textContent = event.level || event.severity || '-'; code.textContent = event.code || '-'; message.textContent = event.message || ''; row.append(level, code, message); box.appendChild(row); }); }
async function refreshDashboard() { try { setConnection('REFRESHING', false); const [health, snapshotResult] = await Promise.allSettled([getJson('/api/cockpit/health'), getJson('/api/cockpit/snapshot')]); state.health = health.status === 'fulfilled' ? health.value : {}; state.snapshot = snapshotResult.status === 'fulfilled' ? snapshotResult.value : {}; state.events = state.snapshot.logs || state.snapshot.operator_actions || []; renderRisk(state.snapshot); renderMetrics(state.snapshot, state.health); renderGuardrails(state.snapshot); renderModel(state.snapshot); renderEvents(state.events); setConnection('CONNECTED', true); } catch (error) { setConnection('API_ERROR', false); renderEvents([{ level: 'ERROR', code: 'CLEAN_DASHBOARD_REFRESH_FAILED', message: error.message }]); } }
$('refreshButton')?.addEventListener('click', refreshDashboard); $('saveSecurityButton')?.addEventListener('click', saveSecurityInputs); loadSecurityInputs(); refreshDashboard(); setInterval(refreshDashboard, 8000);
