# Auto-generated by 4B.4.3.6.6.25Z
# Manual registration helper for Windows Task Scheduler.
# It registers only the no-order shadow collection cycle script.
# Review before running. This script still does not enable paper/live trading.

$ErrorActionPreference = "Stop"
$PackDir = $PSScriptRoot
$ProjectRoot = Split-Path -Parent $PackDir
$TaskName = "TradeBot_HYP005_NoOrderShadowCollection"
$CycleScript = Join-Path $PackDir "run_hyp005_shadow_cycle_no_order.ps1"

$Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$CycleScript`""
$Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddHours(4) -RepetitionInterval (New-TimeSpan -Hours 4) -RepetitionDuration (New-TimeSpan -Days 3650)

# 25Z-H1 compatibility hotfix:
# Some Windows PowerShell ScheduledTasks builds do not expose -DisallowStartIfOnBatteries
# or -AllowStartIfOnBatteries as New-ScheduledTaskSettingsSet parameters. Build the
# settings with only broadly supported parameters, then set optional battery fields
# only when the returned object exposes them.
$Settings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -StartWhenAvailable
$SettingPropertyNames = @($Settings.PSObject.Properties.Name)
if ($SettingPropertyNames -contains "DisallowStartIfOnBatteries") {
  $Settings.DisallowStartIfOnBatteries = $true
}
if ($SettingPropertyNames -contains "StopIfGoingOnBatteries") {
  $Settings.StopIfGoingOnBatteries = $true
}
if ($SettingPropertyNames -contains "AllowStartIfOnBatteries") {
  $Settings.AllowStartIfOnBatteries = $false
}

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Description "HYP-005 no-order shadow collection cycle. No paper/live/order actions." -Force

Write-Host "Registered task: $TaskName"
Write-Host "Cycle script: $CycleScript"
Write-Host "Safety: no paper/live/order actions are enabled by this task."
