# Auto-generated by 4B.4.3.6.6.25Z
# HYP-005 no-order shadow collection cycle.
# Safety: this script does not train, reload, paper trade, live trade, or send orders.

$ErrorActionPreference = "Stop"
$PackDir = $PSScriptRoot
$ReportsDir = Split-Path -Parent $PackDir
$ProjectRoot = Split-Path -Parent $ReportsDir
if (-not (Test-Path (Join-Path $ProjectRoot "tools"))) {
  $ProjectRoot = Split-Path -Parent $PackDir
}
Set-Location $ProjectRoot

$env:PYTHONPATH = "src"
$env:PYTEST_DISABLE_PLUGIN_AUTOLOAD = "1"

Write-Host "[HYP-005] Starting no-order shadow cycle..."

python tools/run_hyp005_shadow_observation_logger_4B436625V.py `
  --candidate-spec-json "reports\4B436625U_hyp005_no_order_shadow_candidate_spec_20260509_175722.json" `
  --symbols "BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT,DOGEUSDT,ADAUSDT,AVAXUSDT,LINKUSDT,LTCUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "reports" `
  --review-ok

python tools/run_hyp005_shadow_collection_orchestrator_4B436625X.py `
  --reports-dir "reports" `
  --include-all `
  --symbols "BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT,DOGEUSDT,ADAUSDT,AVAXUSDT,LINKUSDT,LTCUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "reports" `
  --review-ok

python tools/run_hyp005_shadow_acceptance_readiness_4B436625W.py `
  --reports-dir "reports" `
  --include-all `
  --out-dir "reports" `
  --review-ok

python tools/run_hyp005_shadow_operator_runbook_4B436625Y.py `
  --reports-dir "reports" `
  --include-all `
  --symbols "BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT,DOGEUSDT,ADAUSDT,AVAXUSDT,LINKUSDT,LTCUSDT" `
  --interval "4h" `
  --days 30 `
  --base-url "https://api.binance.com" `
  --out-dir "reports" `
  --review-ok

Write-Host "[HYP-005] No-order shadow cycle completed. Paper/live/order permissions remain closed."
