from __future__ import annotations

OPERATOR_COCKPIT_CONTRACT_VERSION = "4B.4.3.6.6.33A"
OPERATOR_COCKPIT_FOUNDATION_ENABLED = True
OPERATOR_COCKPIT_RUNTIME_HARDENING_VERSION = "4B.4.3.6.6.33B"
OPERATOR_COCKPIT_RUNTIME_HARDENING_ENABLED = True
OPERATOR_COCKPIT_SECURITY_GATE_VERSION = "4B.4.3.6.6.33C"
OPERATOR_COCKPIT_SECURITY_GATE_ENABLED = True

__all__ = [
    "OPERATOR_COCKPIT_CONTRACT_VERSION",
    "OPERATOR_COCKPIT_FOUNDATION_ENABLED",
    "OPERATOR_COCKPIT_RUNTIME_HARDENING_VERSION",
    "OPERATOR_COCKPIT_RUNTIME_HARDENING_ENABLED",
    "OPERATOR_COCKPIT_SECURITY_GATE_VERSION",
    "OPERATOR_COCKPIT_SECURITY_GATE_ENABLED",
]
