from __future__ import annotations

import json
import py_compile
from pathlib import Path

PATCH_ID = "4B436645_49"
PATCH_VERSION = "4B.4.3.6.6.45-49"
PATCH_NAME = "Phase 45-49 Paper Sandbox Transition Bundle"
REQUIRED_FILES = [
    "README_APPLY_4B436645_49_PHASE45_49_BUNDLE.txt",
    "docs/PHASE45_TO_PHASE49_PAPER_SANDBOX_TRANSITION_BUNDLE_4B436645_49.md",
    "src/tradebot/__init__.py",
    "src/tradebot/paper_sandbox_phase45_49_common.py",
    "tests/test_phase45_to_phase49_paper_sandbox_transition_bundle_4B436645_49.py",
    "tools/apply_4B436645_49_phase45_to_phase49_paper_sandbox_transition_bundle.py",
    "tools/check_4B436645_49_phase45_to_phase49_paper_sandbox_transition_bundle.py",
    "tools/run_4B436645_49_phase45_to_phase49_paper_sandbox_transition_bundle.py",
    "tools/rollback_4B436645_49_phase45_to_phase49_paper_sandbox_transition_bundle.py",
    "README_APPLY_4B436645A.txt",
    "docs/PAPER_SANDBOX_ACTUAL_EVIDENCE_INTAKE_REVIEW_4B436645A.md",
    "src/tradebot/paper_sandbox_actual_evidence_intake_review.py",
    "tests/test_paper_sandbox_actual_evidence_intake_review_4B436645A.py",
    "tools/apply_4B436645A_paper_sandbox_actual_evidence_intake_review.py",
    "tools/check_4B436645A_paper_sandbox_actual_evidence_intake_review.py",
    "tools/run_4B436645A_paper_sandbox_actual_evidence_intake_review.py",
    "tools/rollback_4B436645A_paper_sandbox_actual_evidence_intake_review.py",
    "README_APPLY_4B436645B.txt",
    "docs/PAPER_SANDBOX_EXTERNAL_EVIDENCE_MANIFEST_INTAKE_CONTRACT_4B436645B.md",
    "src/tradebot/paper_sandbox_external_evidence_manifest_intake_contract.py",
    "tests/test_paper_sandbox_external_evidence_manifest_intake_contract_4B436645B.py",
    "tools/apply_4B436645B_paper_sandbox_external_evidence_manifest_intake_contract.py",
    "tools/check_4B436645B_paper_sandbox_external_evidence_manifest_intake_contract.py",
    "tools/run_4B436645B_paper_sandbox_external_evidence_manifest_intake_contract.py",
    "tools/rollback_4B436645B_paper_sandbox_external_evidence_manifest_intake_contract.py",
    "README_APPLY_4B436645C.txt",
    "docs/PAPER_SANDBOX_RUNTIME_PRESENCE_EVIDENCE_INTAKE_CRITERIA_4B436645C.md",
    "src/tradebot/paper_sandbox_runtime_presence_evidence_intake_criteria.py",
    "tests/test_paper_sandbox_runtime_presence_evidence_intake_criteria_4B436645C.py",
    "tools/apply_4B436645C_paper_sandbox_runtime_presence_evidence_intake_criteria.py",
    "tools/check_4B436645C_paper_sandbox_runtime_presence_evidence_intake_criteria.py",
    "tools/run_4B436645C_paper_sandbox_runtime_presence_evidence_intake_criteria.py",
    "tools/rollback_4B436645C_paper_sandbox_runtime_presence_evidence_intake_criteria.py",
    "README_APPLY_4B436645D.txt",
    "docs/PAPER_SANDBOX_HEALTH_EVIDENCE_INTAKE_CRITERIA_4B436645D.md",
    "src/tradebot/paper_sandbox_health_evidence_intake_criteria.py",
    "tests/test_paper_sandbox_health_evidence_intake_criteria_4B436645D.py",
    "tools/apply_4B436645D_paper_sandbox_health_evidence_intake_criteria.py",
    "tools/check_4B436645D_paper_sandbox_health_evidence_intake_criteria.py",
    "tools/run_4B436645D_paper_sandbox_health_evidence_intake_criteria.py",
    "tools/rollback_4B436645D_paper_sandbox_health_evidence_intake_criteria.py",
    "README_APPLY_4B436645E.txt",
    "docs/PAPER_SANDBOX_METRICS_EVIDENCE_INTAKE_CRITERIA_4B436645E.md",
    "src/tradebot/paper_sandbox_metrics_evidence_intake_criteria.py",
    "tests/test_paper_sandbox_metrics_evidence_intake_criteria_4B436645E.py",
    "tools/apply_4B436645E_paper_sandbox_metrics_evidence_intake_criteria.py",
    "tools/check_4B436645E_paper_sandbox_metrics_evidence_intake_criteria.py",
    "tools/run_4B436645E_paper_sandbox_metrics_evidence_intake_criteria.py",
    "tools/rollback_4B436645E_paper_sandbox_metrics_evidence_intake_criteria.py",
    "README_APPLY_4B436645F.txt",
    "docs/PAPER_SANDBOX_INCIDENT_BUDGET_EVIDENCE_INTAKE_CRITERIA_4B436645F.md",
    "src/tradebot/paper_sandbox_incident_budget_evidence_intake_criteria.py",
    "tests/test_paper_sandbox_incident_budget_evidence_intake_criteria_4B436645F.py",
    "tools/apply_4B436645F_paper_sandbox_incident_budget_evidence_intake_criteria.py",
    "tools/check_4B436645F_paper_sandbox_incident_budget_evidence_intake_criteria.py",
    "tools/run_4B436645F_paper_sandbox_incident_budget_evidence_intake_criteria.py",
    "tools/rollback_4B436645F_paper_sandbox_incident_budget_evidence_intake_criteria.py",
    "README_APPLY_4B436645G.txt",
    "docs/PAPER_SANDBOX_ZERO_ORDER_INVARIANT_EVIDENCE_INTAKE_CRITERIA_4B436645G.md",
    "src/tradebot/paper_sandbox_zero_order_invariant_evidence_intake_criteria.py",
    "tests/test_paper_sandbox_zero_order_invariant_evidence_intake_criteria_4B436645G.py",
    "tools/apply_4B436645G_paper_sandbox_zero_order_invariant_evidence_intake_criteria.py",
    "tools/check_4B436645G_paper_sandbox_zero_order_invariant_evidence_intake_criteria.py",
    "tools/run_4B436645G_paper_sandbox_zero_order_invariant_evidence_intake_criteria.py",
    "tools/rollback_4B436645G_paper_sandbox_zero_order_invariant_evidence_intake_criteria.py",
    "README_APPLY_4B436645H.txt",
    "docs/PAPER_SANDBOX_ACTUAL_EVIDENCE_INTAKE_DECISION_GATE_4B436645H.md",
    "src/tradebot/paper_sandbox_actual_evidence_intake_decision_gate.py",
    "tests/test_paper_sandbox_actual_evidence_intake_decision_gate_4B436645H.py",
    "tools/apply_4B436645H_paper_sandbox_actual_evidence_intake_decision_gate.py",
    "tools/check_4B436645H_paper_sandbox_actual_evidence_intake_decision_gate.py",
    "tools/run_4B436645H_paper_sandbox_actual_evidence_intake_decision_gate.py",
    "tools/rollback_4B436645H_paper_sandbox_actual_evidence_intake_decision_gate.py",
    "README_APPLY_4B436645I.txt",
    "docs/PAPER_SANDBOX_ACTUAL_EVIDENCE_INTAKE_CLOSURE_4B436645I.md",
    "src/tradebot/paper_sandbox_actual_evidence_intake_closure.py",
    "tests/test_paper_sandbox_actual_evidence_intake_closure_4B436645I.py",
    "tools/apply_4B436645I_paper_sandbox_actual_evidence_intake_closure.py",
    "tools/check_4B436645I_paper_sandbox_actual_evidence_intake_closure.py",
    "tools/run_4B436645I_paper_sandbox_actual_evidence_intake_closure.py",
    "tools/rollback_4B436645I_paper_sandbox_actual_evidence_intake_closure.py",
    "README_APPLY_4B436646A.txt",
    "docs/PAPER_SANDBOX_ACTUAL_NO_ORDER_SOAK_ACCEPTANCE_REVIEW_4B436646A.md",
    "src/tradebot/paper_sandbox_actual_no_order_soak_acceptance_review.py",
    "tests/test_paper_sandbox_actual_no_order_soak_acceptance_review_4B436646A.py",
    "tools/apply_4B436646A_paper_sandbox_actual_no_order_soak_acceptance_review.py",
    "tools/check_4B436646A_paper_sandbox_actual_no_order_soak_acceptance_review.py",
    "tools/run_4B436646A_paper_sandbox_actual_no_order_soak_acceptance_review.py",
    "tools/rollback_4B436646A_paper_sandbox_actual_no_order_soak_acceptance_review.py",
    "README_APPLY_4B436646B.txt",
    "docs/PAPER_SANDBOX_EVIDENCE_MANIFEST_CONSISTENCY_REVIEW_4B436646B.md",
    "src/tradebot/paper_sandbox_evidence_manifest_consistency_review.py",
    "tests/test_paper_sandbox_evidence_manifest_consistency_review_4B436646B.py",
    "tools/apply_4B436646B_paper_sandbox_evidence_manifest_consistency_review.py",
    "tools/check_4B436646B_paper_sandbox_evidence_manifest_consistency_review.py",
    "tools/run_4B436646B_paper_sandbox_evidence_manifest_consistency_review.py",
    "tools/rollback_4B436646B_paper_sandbox_evidence_manifest_consistency_review.py",
    "README_APPLY_4B436646C.txt",
    "docs/PAPER_SANDBOX_RUNTIME_STABILITY_ACCEPTANCE_REVIEW_4B436646C.md",
    "src/tradebot/paper_sandbox_runtime_stability_acceptance_review.py",
    "tests/test_paper_sandbox_runtime_stability_acceptance_review_4B436646C.py",
    "tools/apply_4B436646C_paper_sandbox_runtime_stability_acceptance_review.py",
    "tools/check_4B436646C_paper_sandbox_runtime_stability_acceptance_review.py",
    "tools/run_4B436646C_paper_sandbox_runtime_stability_acceptance_review.py",
    "tools/rollback_4B436646C_paper_sandbox_runtime_stability_acceptance_review.py",
    "README_APPLY_4B436646D.txt",
    "docs/PAPER_SANDBOX_HEALTH_STABILITY_ACCEPTANCE_REVIEW_4B436646D.md",
    "src/tradebot/paper_sandbox_health_stability_acceptance_review.py",
    "tests/test_paper_sandbox_health_stability_acceptance_review_4B436646D.py",
    "tools/apply_4B436646D_paper_sandbox_health_stability_acceptance_review.py",
    "tools/check_4B436646D_paper_sandbox_health_stability_acceptance_review.py",
    "tools/run_4B436646D_paper_sandbox_health_stability_acceptance_review.py",
    "tools/rollback_4B436646D_paper_sandbox_health_stability_acceptance_review.py",
    "README_APPLY_4B436646E.txt",
    "docs/PAPER_SANDBOX_METRICS_INTEGRITY_ACCEPTANCE_REVIEW_4B436646E.md",
    "src/tradebot/paper_sandbox_metrics_integrity_acceptance_review.py",
    "tests/test_paper_sandbox_metrics_integrity_acceptance_review_4B436646E.py",
    "tools/apply_4B436646E_paper_sandbox_metrics_integrity_acceptance_review.py",
    "tools/check_4B436646E_paper_sandbox_metrics_integrity_acceptance_review.py",
    "tools/run_4B436646E_paper_sandbox_metrics_integrity_acceptance_review.py",
    "tools/rollback_4B436646E_paper_sandbox_metrics_integrity_acceptance_review.py",
    "README_APPLY_4B436646F.txt",
    "docs/PAPER_SANDBOX_INCIDENT_BUDGET_ACCEPTANCE_REVIEW_4B436646F.md",
    "src/tradebot/paper_sandbox_incident_budget_acceptance_review.py",
    "tests/test_paper_sandbox_incident_budget_acceptance_review_4B436646F.py",
    "tools/apply_4B436646F_paper_sandbox_incident_budget_acceptance_review.py",
    "tools/check_4B436646F_paper_sandbox_incident_budget_acceptance_review.py",
    "tools/run_4B436646F_paper_sandbox_incident_budget_acceptance_review.py",
    "tools/rollback_4B436646F_paper_sandbox_incident_budget_acceptance_review.py",
    "README_APPLY_4B436646G.txt",
    "docs/PAPER_SANDBOX_ZERO_ORDER_INVARIANT_ACCEPTANCE_REVIEW_4B436646G.md",
    "src/tradebot/paper_sandbox_zero_order_invariant_acceptance_review.py",
    "tests/test_paper_sandbox_zero_order_invariant_acceptance_review_4B436646G.py",
    "tools/apply_4B436646G_paper_sandbox_zero_order_invariant_acceptance_review.py",
    "tools/check_4B436646G_paper_sandbox_zero_order_invariant_acceptance_review.py",
    "tools/run_4B436646G_paper_sandbox_zero_order_invariant_acceptance_review.py",
    "tools/rollback_4B436646G_paper_sandbox_zero_order_invariant_acceptance_review.py",
    "README_APPLY_4B436646H.txt",
    "docs/PAPER_SANDBOX_NO_ORDER_SOAK_ACCEPTANCE_DECISION_GATE_4B436646H.md",
    "src/tradebot/paper_sandbox_no_order_soak_acceptance_decision_gate.py",
    "tests/test_paper_sandbox_no_order_soak_acceptance_decision_gate_4B436646H.py",
    "tools/apply_4B436646H_paper_sandbox_no_order_soak_acceptance_decision_gate.py",
    "tools/check_4B436646H_paper_sandbox_no_order_soak_acceptance_decision_gate.py",
    "tools/run_4B436646H_paper_sandbox_no_order_soak_acceptance_decision_gate.py",
    "tools/rollback_4B436646H_paper_sandbox_no_order_soak_acceptance_decision_gate.py",
    "README_APPLY_4B436646I.txt",
    "docs/PAPER_SANDBOX_ACTUAL_NO_ORDER_SOAK_ACCEPTANCE_CLOSURE_4B436646I.md",
    "src/tradebot/paper_sandbox_actual_no_order_soak_acceptance_closure.py",
    "tests/test_paper_sandbox_actual_no_order_soak_acceptance_closure_4B436646I.py",
    "tools/apply_4B436646I_paper_sandbox_actual_no_order_soak_acceptance_closure.py",
    "tools/check_4B436646I_paper_sandbox_actual_no_order_soak_acceptance_closure.py",
    "tools/run_4B436646I_paper_sandbox_actual_no_order_soak_acceptance_closure.py",
    "tools/rollback_4B436646I_paper_sandbox_actual_no_order_soak_acceptance_closure.py",
    "README_APPLY_4B436647A.txt",
    "docs/PAPER_SANDBOX_PAPER_ORDER_PATH_AUTHORIZATION_REVIEW_4B436647A.md",
    "src/tradebot/paper_sandbox_paper_order_path_authorization_review.py",
    "tests/test_paper_sandbox_paper_order_path_authorization_review_4B436647A.py",
    "tools/apply_4B436647A_paper_sandbox_paper_order_path_authorization_review.py",
    "tools/check_4B436647A_paper_sandbox_paper_order_path_authorization_review.py",
    "tools/run_4B436647A_paper_sandbox_paper_order_path_authorization_review.py",
    "tools/rollback_4B436647A_paper_sandbox_paper_order_path_authorization_review.py",
    "README_APPLY_4B436647B.txt",
    "docs/PAPER_SANDBOX_PAPER_ONLY_ENVIRONMENT_ISOLATION_CRITERIA_4B436647B.md",
    "src/tradebot/paper_sandbox_paper_only_environment_isolation_criteria.py",
    "tests/test_paper_sandbox_paper_only_environment_isolation_criteria_4B436647B.py",
    "tools/apply_4B436647B_paper_sandbox_paper_only_environment_isolation_criteria.py",
    "tools/check_4B436647B_paper_sandbox_paper_only_environment_isolation_criteria.py",
    "tools/run_4B436647B_paper_sandbox_paper_only_environment_isolation_criteria.py",
    "tools/rollback_4B436647B_paper_sandbox_paper_only_environment_isolation_criteria.py",
    "README_APPLY_4B436647C.txt",
    "docs/PAPER_SANDBOX_TESTNET_LIVE_CREDENTIAL_SEPARATION_CRITERIA_4B436647C.md",
    "src/tradebot/paper_sandbox_testnet_live_credential_separation_criteria.py",
    "tests/test_paper_sandbox_testnet_live_credential_separation_criteria_4B436647C.py",
    "tools/apply_4B436647C_paper_sandbox_testnet_live_credential_separation_criteria.py",
    "tools/check_4B436647C_paper_sandbox_testnet_live_credential_separation_criteria.py",
    "tools/run_4B436647C_paper_sandbox_testnet_live_credential_separation_criteria.py",
    "tools/rollback_4B436647C_paper_sandbox_testnet_live_credential_separation_criteria.py",
    "README_APPLY_4B436647D.txt",
    "docs/PAPER_SANDBOX_ORDER_ADAPTER_FAIL_CLOSED_CRITERIA_4B436647D.md",
    "src/tradebot/paper_sandbox_order_adapter_fail_closed_criteria.py",
    "tests/test_paper_sandbox_order_adapter_fail_closed_criteria_4B436647D.py",
    "tools/apply_4B436647D_paper_sandbox_order_adapter_fail_closed_criteria.py",
    "tools/check_4B436647D_paper_sandbox_order_adapter_fail_closed_criteria.py",
    "tools/run_4B436647D_paper_sandbox_order_adapter_fail_closed_criteria.py",
    "tools/rollback_4B436647D_paper_sandbox_order_adapter_fail_closed_criteria.py",
    "README_APPLY_4B436647E.txt",
    "docs/PAPER_SANDBOX_POSITION_SIZING_RISK_CAP_CRITERIA_4B436647E.md",
    "src/tradebot/paper_sandbox_position_sizing_risk_cap_criteria.py",
    "tests/test_paper_sandbox_position_sizing_risk_cap_criteria_4B436647E.py",
    "tools/apply_4B436647E_paper_sandbox_position_sizing_risk_cap_criteria.py",
    "tools/check_4B436647E_paper_sandbox_position_sizing_risk_cap_criteria.py",
    "tools/run_4B436647E_paper_sandbox_position_sizing_risk_cap_criteria.py",
    "tools/rollback_4B436647E_paper_sandbox_position_sizing_risk_cap_criteria.py",
    "README_APPLY_4B436647F.txt",
    "docs/PAPER_SANDBOX_DUPLICATE_ORDER_IDEMPOTENCY_CRITERIA_4B436647F.md",
    "src/tradebot/paper_sandbox_duplicate_order_idempotency_criteria.py",
    "tests/test_paper_sandbox_duplicate_order_idempotency_criteria_4B436647F.py",
    "tools/apply_4B436647F_paper_sandbox_duplicate_order_idempotency_criteria.py",
    "tools/check_4B436647F_paper_sandbox_duplicate_order_idempotency_criteria.py",
    "tools/run_4B436647F_paper_sandbox_duplicate_order_idempotency_criteria.py",
    "tools/rollback_4B436647F_paper_sandbox_duplicate_order_idempotency_criteria.py",
    "README_APPLY_4B436647G.txt",
    "docs/PAPER_SANDBOX_KILL_SWITCH_AND_CIRCUIT_BREAKER_CRITERIA_4B436647G.md",
    "src/tradebot/paper_sandbox_kill_switch_and_circuit_breaker_criteria.py",
    "tests/test_paper_sandbox_kill_switch_and_circuit_breaker_criteria_4B436647G.py",
    "tools/apply_4B436647G_paper_sandbox_kill_switch_and_circuit_breaker_criteria.py",
    "tools/check_4B436647G_paper_sandbox_kill_switch_and_circuit_breaker_criteria.py",
    "tools/run_4B436647G_paper_sandbox_kill_switch_and_circuit_breaker_criteria.py",
    "tools/rollback_4B436647G_paper_sandbox_kill_switch_and_circuit_breaker_criteria.py",
    "README_APPLY_4B436647H.txt",
    "docs/PAPER_SANDBOX_PAPER_ORDER_PATH_AUTHORIZATION_DECISION_GATE_4B436647H.md",
    "src/tradebot/paper_sandbox_paper_order_path_authorization_decision_gate.py",
    "tests/test_paper_sandbox_paper_order_path_authorization_decision_gate_4B436647H.py",
    "tools/apply_4B436647H_paper_sandbox_paper_order_path_authorization_decision_gate.py",
    "tools/check_4B436647H_paper_sandbox_paper_order_path_authorization_decision_gate.py",
    "tools/run_4B436647H_paper_sandbox_paper_order_path_authorization_decision_gate.py",
    "tools/rollback_4B436647H_paper_sandbox_paper_order_path_authorization_decision_gate.py",
    "README_APPLY_4B436647I.txt",
    "docs/PAPER_SANDBOX_PAPER_ORDER_PATH_AUTHORIZATION_CLOSURE_4B436647I.md",
    "src/tradebot/paper_sandbox_paper_order_path_authorization_closure.py",
    "tests/test_paper_sandbox_paper_order_path_authorization_closure_4B436647I.py",
    "tools/apply_4B436647I_paper_sandbox_paper_order_path_authorization_closure.py",
    "tools/check_4B436647I_paper_sandbox_paper_order_path_authorization_closure.py",
    "tools/run_4B436647I_paper_sandbox_paper_order_path_authorization_closure.py",
    "tools/rollback_4B436647I_paper_sandbox_paper_order_path_authorization_closure.py",
    "README_APPLY_4B436648A.txt",
    "docs/PAPER_SANDBOX_PAPER_ORDER_DRY_RUN_CONTRACT_REVIEW_4B436648A.md",
    "src/tradebot/paper_sandbox_paper_order_dry_run_contract_review.py",
    "tests/test_paper_sandbox_paper_order_dry_run_contract_review_4B436648A.py",
    "tools/apply_4B436648A_paper_sandbox_paper_order_dry_run_contract_review.py",
    "tools/check_4B436648A_paper_sandbox_paper_order_dry_run_contract_review.py",
    "tools/run_4B436648A_paper_sandbox_paper_order_dry_run_contract_review.py",
    "tools/rollback_4B436648A_paper_sandbox_paper_order_dry_run_contract_review.py",
    "README_APPLY_4B436648B.txt",
    "docs/PAPER_SANDBOX_SIGNAL_TO_INTENDED_ORDER_MAPPING_CONTRACT_4B436648B.md",
    "src/tradebot/paper_sandbox_signal_to_intended_order_mapping_contract.py",
    "tests/test_paper_sandbox_signal_to_intended_order_mapping_contract_4B436648B.py",
    "tools/apply_4B436648B_paper_sandbox_signal_to_intended_order_mapping_contract.py",
    "tools/check_4B436648B_paper_sandbox_signal_to_intended_order_mapping_contract.py",
    "tools/run_4B436648B_paper_sandbox_signal_to_intended_order_mapping_contract.py",
    "tools/rollback_4B436648B_paper_sandbox_signal_to_intended_order_mapping_contract.py",
    "README_APPLY_4B436648C.txt",
    "docs/PAPER_SANDBOX_ORDER_SCHEMA_VALIDATION_CONTRACT_4B436648C.md",
    "src/tradebot/paper_sandbox_order_schema_validation_contract.py",
    "tests/test_paper_sandbox_order_schema_validation_contract_4B436648C.py",
    "tools/apply_4B436648C_paper_sandbox_order_schema_validation_contract.py",
    "tools/check_4B436648C_paper_sandbox_order_schema_validation_contract.py",
    "tools/run_4B436648C_paper_sandbox_order_schema_validation_contract.py",
    "tools/rollback_4B436648C_paper_sandbox_order_schema_validation_contract.py",
    "README_APPLY_4B436648D.txt",
    "docs/PAPER_SANDBOX_QUANTITY_NOTIONAL_RISK_CAP_DRY_RUN_CONTRACT_4B436648D.md",
    "src/tradebot/paper_sandbox_quantity_notional_risk_cap_dry_run_contract.py",
    "tests/test_paper_sandbox_quantity_notional_risk_cap_dry_run_contract_4B436648D.py",
    "tools/apply_4B436648D_paper_sandbox_quantity_notional_risk_cap_dry_run_contract.py",
    "tools/check_4B436648D_paper_sandbox_quantity_notional_risk_cap_dry_run_contract.py",
    "tools/run_4B436648D_paper_sandbox_quantity_notional_risk_cap_dry_run_contract.py",
    "tools/rollback_4B436648D_paper_sandbox_quantity_notional_risk_cap_dry_run_contract.py",
    "README_APPLY_4B436648E.txt",
    "docs/PAPER_SANDBOX_PROTECTIVE_EXIT_DRY_RUN_CONTRACT_4B436648E.md",
    "src/tradebot/paper_sandbox_protective_exit_dry_run_contract.py",
    "tests/test_paper_sandbox_protective_exit_dry_run_contract_4B436648E.py",
    "tools/apply_4B436648E_paper_sandbox_protective_exit_dry_run_contract.py",
    "tools/check_4B436648E_paper_sandbox_protective_exit_dry_run_contract.py",
    "tools/run_4B436648E_paper_sandbox_protective_exit_dry_run_contract.py",
    "tools/rollback_4B436648E_paper_sandbox_protective_exit_dry_run_contract.py",
    "README_APPLY_4B436648F.txt",
    "docs/PAPER_SANDBOX_RECONCILIATION_DRY_RUN_CONTRACT_4B436648F.md",
    "src/tradebot/paper_sandbox_reconciliation_dry_run_contract.py",
    "tests/test_paper_sandbox_reconciliation_dry_run_contract_4B436648F.py",
    "tools/apply_4B436648F_paper_sandbox_reconciliation_dry_run_contract.py",
    "tools/check_4B436648F_paper_sandbox_reconciliation_dry_run_contract.py",
    "tools/run_4B436648F_paper_sandbox_reconciliation_dry_run_contract.py",
    "tools/rollback_4B436648F_paper_sandbox_reconciliation_dry_run_contract.py",
    "README_APPLY_4B436648G.txt",
    "docs/PAPER_SANDBOX_AUDIT_TRAIL_DRY_RUN_CONTRACT_4B436648G.md",
    "src/tradebot/paper_sandbox_audit_trail_dry_run_contract.py",
    "tests/test_paper_sandbox_audit_trail_dry_run_contract_4B436648G.py",
    "tools/apply_4B436648G_paper_sandbox_audit_trail_dry_run_contract.py",
    "tools/check_4B436648G_paper_sandbox_audit_trail_dry_run_contract.py",
    "tools/run_4B436648G_paper_sandbox_audit_trail_dry_run_contract.py",
    "tools/rollback_4B436648G_paper_sandbox_audit_trail_dry_run_contract.py",
    "README_APPLY_4B436648H.txt",
    "docs/PAPER_SANDBOX_PAPER_ORDER_DRY_RUN_ACCEPTANCE_GATE_4B436648H.md",
    "src/tradebot/paper_sandbox_paper_order_dry_run_acceptance_gate.py",
    "tests/test_paper_sandbox_paper_order_dry_run_acceptance_gate_4B436648H.py",
    "tools/apply_4B436648H_paper_sandbox_paper_order_dry_run_acceptance_gate.py",
    "tools/check_4B436648H_paper_sandbox_paper_order_dry_run_acceptance_gate.py",
    "tools/run_4B436648H_paper_sandbox_paper_order_dry_run_acceptance_gate.py",
    "tools/rollback_4B436648H_paper_sandbox_paper_order_dry_run_acceptance_gate.py",
    "README_APPLY_4B436648I.txt",
    "docs/PAPER_SANDBOX_PAPER_ORDER_DRY_RUN_CONTRACT_CLOSURE_4B436648I.md",
    "src/tradebot/paper_sandbox_paper_order_dry_run_contract_closure.py",
    "tests/test_paper_sandbox_paper_order_dry_run_contract_closure_4B436648I.py",
    "tools/apply_4B436648I_paper_sandbox_paper_order_dry_run_contract_closure.py",
    "tools/check_4B436648I_paper_sandbox_paper_order_dry_run_contract_closure.py",
    "tools/run_4B436648I_paper_sandbox_paper_order_dry_run_contract_closure.py",
    "tools/rollback_4B436648I_paper_sandbox_paper_order_dry_run_contract_closure.py",
    "README_APPLY_4B436649A.txt",
    "docs/PAPER_SANDBOX_CONTROLLED_PAPER_SUBMIT_ENABLEMENT_REVIEW_4B436649A.md",
    "src/tradebot/paper_sandbox_controlled_paper_submit_enablement_review.py",
    "tests/test_paper_sandbox_controlled_paper_submit_enablement_review_4B436649A.py",
    "tools/apply_4B436649A_paper_sandbox_controlled_paper_submit_enablement_review.py",
    "tools/check_4B436649A_paper_sandbox_controlled_paper_submit_enablement_review.py",
    "tools/run_4B436649A_paper_sandbox_controlled_paper_submit_enablement_review.py",
    "tools/rollback_4B436649A_paper_sandbox_controlled_paper_submit_enablement_review.py",
    "README_APPLY_4B436649B.txt",
    "docs/PAPER_SANDBOX_PAPER_ENDPOINT_ISOLATION_REVIEW_4B436649B.md",
    "src/tradebot/paper_sandbox_paper_endpoint_isolation_review.py",
    "tests/test_paper_sandbox_paper_endpoint_isolation_review_4B436649B.py",
    "tools/apply_4B436649B_paper_sandbox_paper_endpoint_isolation_review.py",
    "tools/check_4B436649B_paper_sandbox_paper_endpoint_isolation_review.py",
    "tools/run_4B436649B_paper_sandbox_paper_endpoint_isolation_review.py",
    "tools/rollback_4B436649B_paper_sandbox_paper_endpoint_isolation_review.py",
    "README_APPLY_4B436649C.txt",
    "docs/PAPER_SANDBOX_PAPER_CREDENTIAL_PERMISSION_REVIEW_4B436649C.md",
    "src/tradebot/paper_sandbox_paper_credential_permission_review.py",
    "tests/test_paper_sandbox_paper_credential_permission_review_4B436649C.py",
    "tools/apply_4B436649C_paper_sandbox_paper_credential_permission_review.py",
    "tools/check_4B436649C_paper_sandbox_paper_credential_permission_review.py",
    "tools/run_4B436649C_paper_sandbox_paper_credential_permission_review.py",
    "tools/rollback_4B436649C_paper_sandbox_paper_credential_permission_review.py",
    "README_APPLY_4B436649D.txt",
    "docs/PAPER_SANDBOX_MAX_SYMBOL_POSITION_TRADE_LIMIT_REVIEW_4B436649D.md",
    "src/tradebot/paper_sandbox_max_symbol_position_trade_limit_review.py",
    "tests/test_paper_sandbox_max_symbol_position_trade_limit_review_4B436649D.py",
    "tools/apply_4B436649D_paper_sandbox_max_symbol_position_trade_limit_review.py",
    "tools/check_4B436649D_paper_sandbox_max_symbol_position_trade_limit_review.py",
    "tools/run_4B436649D_paper_sandbox_max_symbol_position_trade_limit_review.py",
    "tools/rollback_4B436649D_paper_sandbox_max_symbol_position_trade_limit_review.py",
    "README_APPLY_4B436649E.txt",
    "docs/PAPER_SANDBOX_DAILY_LOSS_KILL_SWITCH_LIMIT_REVIEW_4B436649E.md",
    "src/tradebot/paper_sandbox_daily_loss_kill_switch_limit_review.py",
    "tests/test_paper_sandbox_daily_loss_kill_switch_limit_review_4B436649E.py",
    "tools/apply_4B436649E_paper_sandbox_daily_loss_kill_switch_limit_review.py",
    "tools/check_4B436649E_paper_sandbox_daily_loss_kill_switch_limit_review.py",
    "tools/run_4B436649E_paper_sandbox_daily_loss_kill_switch_limit_review.py",
    "tools/rollback_4B436649E_paper_sandbox_daily_loss_kill_switch_limit_review.py",
    "README_APPLY_4B436649F.txt",
    "docs/PAPER_SANDBOX_PAPER_SUBMIT_AUDIT_RECONCILIATION_REVIEW_4B436649F.md",
    "src/tradebot/paper_sandbox_paper_submit_audit_reconciliation_review.py",
    "tests/test_paper_sandbox_paper_submit_audit_reconciliation_review_4B436649F.py",
    "tools/apply_4B436649F_paper_sandbox_paper_submit_audit_reconciliation_review.py",
    "tools/check_4B436649F_paper_sandbox_paper_submit_audit_reconciliation_review.py",
    "tools/run_4B436649F_paper_sandbox_paper_submit_audit_reconciliation_review.py",
    "tools/rollback_4B436649F_paper_sandbox_paper_submit_audit_reconciliation_review.py",
    "README_APPLY_4B436649G.txt",
    "docs/PAPER_SANDBOX_PAPER_SUBMIT_FAIL_CLOSED_ROLLBACK_REVIEW_4B436649G.md",
    "src/tradebot/paper_sandbox_paper_submit_fail_closed_rollback_review.py",
    "tests/test_paper_sandbox_paper_submit_fail_closed_rollback_review_4B436649G.py",
    "tools/apply_4B436649G_paper_sandbox_paper_submit_fail_closed_rollback_review.py",
    "tools/check_4B436649G_paper_sandbox_paper_submit_fail_closed_rollback_review.py",
    "tools/run_4B436649G_paper_sandbox_paper_submit_fail_closed_rollback_review.py",
    "tools/rollback_4B436649G_paper_sandbox_paper_submit_fail_closed_rollback_review.py",
    "README_APPLY_4B436649H.txt",
    "docs/PAPER_SANDBOX_CONTROLLED_PAPER_SUBMIT_ENABLEMENT_DECISION_GATE_4B436649H.md",
    "src/tradebot/paper_sandbox_controlled_paper_submit_enablement_decision_gate.py",
    "tests/test_paper_sandbox_controlled_paper_submit_enablement_decision_gate_4B436649H.py",
    "tools/apply_4B436649H_paper_sandbox_controlled_paper_submit_enablement_decision_gate.py",
    "tools/check_4B436649H_paper_sandbox_controlled_paper_submit_enablement_decision_gate.py",
    "tools/run_4B436649H_paper_sandbox_controlled_paper_submit_enablement_decision_gate.py",
    "tools/rollback_4B436649H_paper_sandbox_controlled_paper_submit_enablement_decision_gate.py",
    "README_APPLY_4B436649I.txt",
    "docs/PAPER_SANDBOX_CONTROLLED_PAPER_SUBMIT_ENABLEMENT_CLOSURE_4B436649I.md",
    "src/tradebot/paper_sandbox_controlled_paper_submit_enablement_closure.py",
    "tests/test_paper_sandbox_controlled_paper_submit_enablement_closure_4B436649I.py",
    "tools/apply_4B436649I_paper_sandbox_controlled_paper_submit_enablement_closure.py",
    "tools/check_4B436649I_paper_sandbox_controlled_paper_submit_enablement_closure.py",
    "tools/run_4B436649I_paper_sandbox_controlled_paper_submit_enablement_closure.py",
    "tools/rollback_4B436649I_paper_sandbox_controlled_paper_submit_enablement_closure.py"
]

COMPILE_FILES = [
    "src/tradebot/paper_sandbox_phase45_49_common.py",
    "tests/test_phase45_to_phase49_paper_sandbox_transition_bundle_4B436645_49.py",
    "tools/check_4B436645_49_phase45_to_phase49_paper_sandbox_transition_bundle.py",
    "tools/run_4B436645_49_phase45_to_phase49_paper_sandbox_transition_bundle.py",
] + [path for path in REQUIRED_FILES if path.startswith("src/tradebot/") or path.startswith("tests/") or path.startswith("tools/check_") or path.startswith("tools/run_")]


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    missing = [path for path in REQUIRED_FILES if not (root / path).exists()]
    compile_errors: dict[str, str] = {}
    for rel in sorted(set(COMPILE_FILES)):
        if rel.endswith(".py") and (root / rel).exists():
            try:
                py_compile.compile(str(root / rel), doraise=True)
            except Exception as exc:  # pragma: no cover
                compile_errors[rel] = str(exc)
    payload = {
        "applied": not missing and not compile_errors,
        "patch_id": PATCH_ID,
        "patch_name": PATCH_NAME,
        "patch_version": PATCH_VERSION,
        "missing_files": missing,
        "compile_errors": compile_errors,
        "py_compile_ok": not compile_errors,
        "phase45_49_bundle_source_mutation_performed": True,
        "phase_count": 45,
        "phase_ids": ['4B436645A', '4B436645B', '4B436645C', '4B436645D', '4B436645E', '4B436645F', '4B436645G', '4B436645H', '4B436645I', '4B436646A', '4B436646B', '4B436646C', '4B436646D', '4B436646E', '4B436646F', '4B436646G', '4B436646H', '4B436646I', '4B436647A', '4B436647B', '4B436647C', '4B436647D', '4B436647E', '4B436647F', '4B436647G', '4B436647H', '4B436647I', '4B436648A', '4B436648B', '4B436648C', '4B436648D', '4B436648E', '4B436648F', '4B436648G', '4B436648H', '4B436648I', '4B436649A', '4B436649B', '4B436649C', '4B436649D', '4B436649E', '4B436649F', '4B436649G', '4B436649H', '4B436649I'],
        "actual_evidence_ingested_by_patch": False,
        "actual_evidence_accepted_by_patch": False,
        "soak_accepted_by_patch": False,
        "paper_order_path_opened_by_patch": False,
        "dry_run_execution_performed_by_patch": False,
        "paper_submit_enabled_by_patch": False,
        "paper_submit_allowed": False,
        "paper_submit_performed": False,
        "paper_order_submit_performed": False,
        "paper_runtime_start_performed": False,
        "network_order_submit_performed": False,
        "network_request_performed": False,
        "network_submit_allowed": False,
        "runtime_start_performed": False,
        "runtime_process_start_performed": False,
        "runtime_start_command_executed": False,
        "runtime_start_command_execution_performed": False,
        "approved_for_live_real": False,
        "approved_for_exchange_submit": False,
        "exchange_submit_performed": False,
        "signed_request_performed": False,
        "training_performed": False,
        "reload_performed": False,
        "runtime_overlay_activated": False,
        "transition_to_next_phase_performed": False,
        "next_phase_unlock_performed": False,
        "file_delete_performed": False,
        "file_move_performed": False,
        "destructive_cleanup_performed": False,
        "git_add_performed": False,
        "git_commit_performed": False,
        "git_push_performed": False,
        "git_tag_performed": False,
        "written_files": REQUIRED_FILES,
    }
    print(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False))
    return 0 if payload["applied"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
