from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

PATCH_ID = "4B436637B"
PATCH_VERSION = "4B.4.3.6.6.37B"
PATCH_NAME = "Install Contract Alignment"
CHECK_NAME = "install_contract_alignment"
READY_DECISION = "INSTALL_CONTRACT_ALIGNMENT_READY_NO_SUBMIT_PRODUCTION_HARDENING_P0_1_LOCKED"
NOT_READY_DECISION = "INSTALL_CONTRACT_ALIGNMENT_NOT_READY_NO_SUBMIT_LOCKED"
NEXT_PHASE = "4B.4.3.6.6.37C"
SOURCE_37A_PATTERN = "4B436637A_post_phase_36_production_readiness_rebaseline_*_ready.json"
README_MARKER_START = "<!-- 4B436637B_INSTALL_CONTRACT_START -->"
README_MARKER_END = "<!-- 4B436637B_INSTALL_CONTRACT_END -->"
REQUIREMENTS_HEADER = (
    "# Generated by 4B.4.3.6.6.37B Install Contract Alignment\n"
    "# Source of truth: pyproject.toml [project].dependencies\n"
    "# Do not add trading/runtime secrets here.\n"
)

NO_SUBMIT_FALSE_FLAGS: tuple[str, ...] = (
    "approved_for_exchange_submit",
    "approved_for_live_real",
    "approved_for_paper_transition",
    "approved_for_runtime_overlay",
    "archive_execution_allowed",
    "archive_move_performed",
    "deduplication_action_performed",
    "destructive_cleanup_performed",
    "evidence_collection_started",
    "exchange_submit_allowed",
    "exchange_submit_performed",
    "fee_slippage_mutation_performed",
    "file_delete_performed",
    "file_move_performed",
    "http_request_performed",
    "live_environment_enabled",
    "live_real_submit_allowed",
    "network_request_allowed_now",
    "network_request_performed",
    "network_submit_allowed",
    "next_phase_unlock_allowed",
    "next_phase_unlock_performed",
    "operator_observation_authorization_unlocked",
    "operator_observation_token_consumed",
    "operator_observation_token_validated",
    "order_submit_performed",
    "p0_hardening_auto_close_allowed",
    "paper_environment_enabled",
    "paper_submit_allowed",
    "paper_transition_approval_performed",
    "paper_transition_ready",
    "paper_transition_unblocked",
    "phase_37_execution_started",
    "phase_37_unlocked",
    "phase_reopen_allowed",
    "phase_reopen_performed",
    "private_account_read_performed",
    "private_api_access_allowed",
    "promotion_gate_mutation_performed",
    "public_data_fetch_adapter_executed",
    "public_market_data_collection_performed",
    "public_observation_dry_run_collector_executed",
    "public_observation_execution_performed",
    "public_observation_network_off_execution_package_executed",
    "reload_performed",
    "repo_hygiene_cleanup_performed",
    "report_commit_policy_mutation_performed",
    "report_delete_performed",
    "runtime_evidence_artifact_written",
    "runtime_evidence_collection_performed",
    "runtime_health_probe_performed",
    "runtime_lock_mutation_performed",
    "runtime_overlay_activated",
    "runtime_overlay_allowed",
    "runtime_probe_performed",
    "runtime_readiness_unlock_performed",
    "signed_request_performed",
    "simulated_approval_performed",
    "sqlite_schema_mutation_performed",
    "strict_config_mutation_performed",
    "trading_action_performed",
    "training_performed",
    "transition_to_next_phase_allowed",
    "transition_to_next_phase_performed",
    "typed_confirmation_mutation_performed",
)

# File mutations are intentionally limited to install-contract alignment only.
NON_TRADING_ALIGNMENT_FLAGS: tuple[str, ...] = (
    "install_contract_mutation_performed",
    "requirements_alignment_mutation_performed",
    "readme_install_contract_mutation_performed",
    "launcher_install_contract_mutation_performed",
)

LAUNCHER_CANDIDATES: tuple[str, ...] = (
    "run_dashboard.ps1",
    "run_dashboard.bat",
    "start_dashboard.ps1",
    "start_dashboard.bat",
    "tools/run_dashboard.ps1",
    "tools/run_dashboard.bat",
    "tools/start_dashboard.ps1",
    "tools/start_dashboard.bat",
)

P0_GAPS_AFTER_37B: tuple[dict[str, Any], ...] = (
    {"gap_id": "P0_INSTALL_CONTRACT_ALIGNMENT", "closed": True, "domain": "install_contract", "closed_by": PATCH_VERSION},
    {"gap_id": "P0_REPO_HYGIENE_EVIDENCE_RETENTION", "closed": False, "domain": "repo_hygiene", "closed_by": None},
    {"gap_id": "P0_STRICT_CONFIG_UNKNOWN_KEY_FAIL_CLOSED", "closed": False, "domain": "strict_config", "closed_by": None},
    {"gap_id": "P0_API_AUTH_DESTRUCTIVE_ENDPOINT_GUARD", "closed": False, "domain": "api_security", "closed_by": None},
    {"gap_id": "P0_TYPED_CONFIRMATION_DESTRUCTIVE_ACTIONS", "closed": False, "domain": "operator_controls", "closed_by": None},
    {"gap_id": "P0_SQLITE_AUDIT_BASELINE", "closed": False, "domain": "persistence", "closed_by": None},
    {"gap_id": "P0_RUNTIME_PROCESS_LOCK", "closed": False, "domain": "runtime_safety", "closed_by": None},
    {"gap_id": "P0_FEE_SLIPPAGE_BASELINE", "closed": False, "domain": "execution_cost_model", "closed_by": None},
    {"gap_id": "P0_REPORT_COMMIT_POLICY", "closed": False, "domain": "evidence_governance", "closed_by": None},
    {"gap_id": "P0_PROMOTION_GATE_ISOLATION", "closed": False, "domain": "promotion_governance", "closed_by": None},
)


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def stable_digest(payload: Mapping[str, Any] | Sequence[Any]) -> str:
    encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"JSON root is not an object: {path}")
    return data


def write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


def latest_report(reports_dir: Path, pattern: str) -> Path | None:
    if not reports_dir.exists():
        return None
    matches = [path for path in reports_dir.glob(pattern) if path.is_file()]
    if not matches:
        return None
    return max(matches, key=lambda path: (path.stat().st_mtime_ns, path.name))


def truthy_violations(source: Mapping[str, Any], flags: Iterable[str]) -> list[str]:
    return [name for name in flags if bool(source.get(name, False))]


@dataclass(frozen=True)
class GitState:
    git_available: bool
    git_branch: str | None
    git_head_short: str | None
    local_phase_37_tags: tuple[str, ...]


def _run_git(args: Sequence[str], cwd: Path, timeout: int = 20) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        text=True,
        capture_output=True,
        timeout=timeout,
        check=False,
    )


def read_git_state(repo_root: Path) -> GitState:
    try:
        branch_result = _run_git(["rev-parse", "--abbrev-ref", "HEAD"], repo_root)
        head_result = _run_git(["rev-parse", "--short", "HEAD"], repo_root)
        phase37_result = _run_git(["tag", "--list", "4B.4.3.6.6.37*"], repo_root)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return GitState(False, None, None, tuple())

    git_available = branch_result.returncode == 0 and head_result.returncode == 0
    branch = branch_result.stdout.strip() if branch_result.returncode == 0 else None
    head = head_result.stdout.strip() if head_result.returncode == 0 else None
    phase37_tags = tuple(sorted(line.strip() for line in phase37_result.stdout.splitlines() if line.strip())) if phase37_result.returncode == 0 else tuple()
    return GitState(git_available, branch, head, phase37_tags)


def _strip_inline_comment(line: str) -> str:
    in_quote: str | None = None
    escaped = False
    result: list[str] = []
    for char in line:
        if escaped:
            result.append(char)
            escaped = False
            continue
        if char == "\\":
            result.append(char)
            escaped = True
            continue
        if char in {"'", '"'}:
            if in_quote == char:
                in_quote = None
            elif in_quote is None:
                in_quote = char
            result.append(char)
            continue
        if char == "#" and in_quote is None:
            break
        result.append(char)
    return "".join(result).strip()


def _parse_toml_string_array(raw: str) -> list[str]:
    values: list[str] = []
    for match in re.finditer(r"(['\"])(.*?)\1", raw, flags=re.DOTALL):
        value = match.group(2).strip()
        if value:
            values.append(value)
    return values


def _extract_project_dependencies_with_tomllib(pyproject_path: Path) -> list[str] | None:
    try:
        import tomllib  # type: ignore[import-not-found]
    except ModuleNotFoundError:  # Python 3.10 fallback below.
        return None
    try:
        data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    except Exception:
        return None
    project = data.get("project")
    if not isinstance(project, dict):
        return []
    dependencies = project.get("dependencies", [])
    if not isinstance(dependencies, list):
        return []
    return [str(item).strip() for item in dependencies if str(item).strip()]


def extract_project_dependencies(pyproject_path: Path) -> list[str]:
    if not pyproject_path.exists():
        return []
    parsed = _extract_project_dependencies_with_tomllib(pyproject_path)
    if parsed is not None:
        return sorted(dict.fromkeys(parsed), key=str.lower)

    text = pyproject_path.read_text(encoding="utf-8")
    project_match = re.search(r"(?ms)^\[project\]\s*(.*?)(?=^\[[^\]]+\]|\Z)", text)
    if not project_match:
        return []
    project_body = project_match.group(1)
    dep_match = re.search(r"(?ms)^dependencies\s*=\s*\[(.*?)\]", project_body)
    if not dep_match:
        return []
    return sorted(dict.fromkeys(_parse_toml_string_array(dep_match.group(1))), key=str.lower)


def normalize_requirement_name(requirement: str) -> str:
    req = requirement.strip()
    if not req:
        return ""
    if req.startswith("-"):
        return req.lower()
    req = req.split(";", 1)[0].strip()
    req = re.split(r"\s*(?:==|>=|<=|~=|!=|>|<|===)\s*", req, maxsplit=1)[0].strip()
    req = req.split("[", 1)[0].strip()
    return re.sub(r"[-_.]+", "-", req).lower()


def parse_requirements(path: Path) -> list[str]:
    if not path.exists():
        return []
    items: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = _strip_inline_comment(raw_line)
        if line:
            items.append(line)
    return items


def render_requirements(dependencies: Sequence[str]) -> str:
    normalized = [dep.strip() for dep in dependencies if dep.strip()]
    ordered = sorted(dict.fromkeys(normalized), key=str.lower)
    return REQUIREMENTS_HEADER + "\n".join(ordered) + ("\n" if ordered else "")


def expected_requirements_digest(dependencies: Sequence[str]) -> str:
    return hashlib.sha256(render_requirements(dependencies).encode("utf-8")).hexdigest()


def requirements_alignment(pyproject_dependencies: Sequence[str], requirements_items: Sequence[str]) -> dict[str, Any]:
    py_by_name = {normalize_requirement_name(dep): dep for dep in pyproject_dependencies if normalize_requirement_name(dep)}
    req_by_name = {normalize_requirement_name(req): req for req in requirements_items if normalize_requirement_name(req)}
    missing_names = sorted(set(py_by_name) - set(req_by_name))
    extra_names = sorted(name for name in set(req_by_name) - set(py_by_name) if not name.startswith("-"))
    mismatch_count = len(missing_names) + len(extra_names)
    return {
        "pyproject_dependency_count": len(pyproject_dependencies),
        "requirements_dependency_count": len(requirements_items),
        "requirements_missing_from_pyproject_dependency_names": missing_names,
        "requirements_extra_dependency_names": extra_names,
        "requirements_pyproject_mismatch_count": mismatch_count,
        "requirements_pyproject_aligned": mismatch_count == 0 and len(pyproject_dependencies) > 0,
    }


def readme_install_contract_block() -> str:
    return f"""{README_MARKER_START}

## Install Contract — 4B.4.3.6.6.37B

Canonical dependency source is `pyproject.toml` `[project].dependencies`.
`requirements.txt` is a generated compatibility file for Windows launcher and quick-start flows.

```powershell
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
```

No paper/live/live-real, runtime overlay, training, reload, or order-submit permission is granted by this install contract.

{README_MARKER_END}
"""


def upsert_readme_block(text: str) -> tuple[str, bool]:
    block = readme_install_contract_block()
    if README_MARKER_START in text and README_MARKER_END in text:
        pattern = re.compile(re.escape(README_MARKER_START) + r".*?" + re.escape(README_MARKER_END), re.DOTALL)
        new_text = pattern.sub(block.strip(), text)
        if not new_text.endswith("\n"):
            new_text += "\n"
        return new_text, new_text != text
    separator = "\n" if text.endswith("\n") else "\n\n"
    return text + separator + block, True


def patch_launcher_text(path: Path, text: str) -> tuple[str, bool]:
    original = text
    replacements = [
        ("pip install -r requirements.txt", "python -m pip install -r requirements.txt"),
        ("pip3 install -r requirements.txt", "python -m pip install -r requirements.txt"),
        ("py -m pip install -r requirements.txt", "python -m pip install -r requirements.txt"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    if "4B436637B install contract" not in text:
        comment = "REM 4B436637B install contract: requirements.txt is generated from pyproject.toml\n" if path.suffix.lower() == ".bat" else "# 4B436637B install contract: requirements.txt is generated from pyproject.toml\n"
        text = comment + text
    return text, text != original


def backup_file(path: Path, backup_root: Path, repo_root: Path) -> Path:
    try:
        relative_path = path.resolve().relative_to(repo_root.resolve())
    except ValueError:
        relative_path = Path(path.name)
    backup_path = backup_root / relative_path
    backup_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, backup_path)
    return backup_path


def apply_install_contract_alignment(repo_root: Path) -> dict[str, Any]:
    repo_root = repo_root.resolve()
    stamp = utc_stamp()
    backup_root = repo_root / "tools" / f"_patch_backup_{PATCH_ID}_{stamp}"
    pyproject_path = repo_root / "pyproject.toml"
    requirements_path = repo_root / "requirements.txt"
    readme_path = repo_root / "README.md"
    dependencies = extract_project_dependencies(pyproject_path)

    mutated_files: list[str] = []
    backed_up_files: list[str] = []
    warnings: list[str] = []

    if dependencies:
        expected_text = render_requirements(dependencies)
        existing_text = requirements_path.read_text(encoding="utf-8") if requirements_path.exists() else ""
        if existing_text != expected_text:
            if requirements_path.exists():
                backup_file(requirements_path, backup_root, repo_root)
                backed_up_files.append("requirements.txt")
            requirements_path.write_text(expected_text, encoding="utf-8")
            mutated_files.append("requirements.txt")
    else:
        warnings.append("pyproject_dependencies_missing_or_empty")

    if readme_path.exists():
        readme_text = readme_path.read_text(encoding="utf-8")
        new_readme, changed = upsert_readme_block(readme_text)
        if changed:
            backup_file(readme_path, backup_root, repo_root)
            backed_up_files.append("README.md")
            readme_path.write_text(new_readme, encoding="utf-8")
            mutated_files.append("README.md")
    else:
        warnings.append("README.md_missing")

    launcher_mutations: list[str] = []
    for rel_path in LAUNCHER_CANDIDATES:
        launcher_path = repo_root / rel_path
        if not launcher_path.exists() or not launcher_path.is_file():
            continue
        launcher_text = launcher_path.read_text(encoding="utf-8")
        new_launcher, changed = patch_launcher_text(launcher_path, launcher_text)
        if changed:
            backup_file(launcher_path, backup_root, repo_root)
            backed_up_files.append(rel_path)
            launcher_path.write_text(new_launcher, encoding="utf-8")
            mutated_files.append(rel_path)
            launcher_mutations.append(rel_path)

    result = {
        "patch_id": PATCH_ID,
        "patch_version": PATCH_VERSION,
        "install_contract_apply_performed": True,
        "install_contract_mutation_performed": bool(mutated_files),
        "requirements_alignment_mutation_performed": "requirements.txt" in mutated_files,
        "readme_install_contract_mutation_performed": "README.md" in mutated_files,
        "launcher_install_contract_mutation_performed": bool(launcher_mutations),
        "modified_files": mutated_files,
        "backed_up_files": backed_up_files,
        "backup_root": str(backup_root.relative_to(repo_root)) if backed_up_files else "",
        "pyproject_dependency_count": len(dependencies),
        "requirements_expected_digest": expected_requirements_digest(dependencies) if dependencies else None,
        "warnings": warnings,
        "file_delete_performed": False,
        "file_move_performed": False,
        "destructive_cleanup_performed": False,
        "order_submit_performed": False,
        "exchange_submit_performed": False,
        "trading_action_performed": False,
        "network_request_performed": False,
        "http_request_performed": False,
        "signed_request_performed": False,
        "runtime_overlay_activated": False,
        "training_performed": False,
        "reload_performed": False,
    }
    return result


def audit_install_contract(repo_root: Path) -> dict[str, Any]:
    repo_root = repo_root.resolve()
    pyproject_path = repo_root / "pyproject.toml"
    requirements_path = repo_root / "requirements.txt"
    readme_path = repo_root / "README.md"
    dependencies = extract_project_dependencies(pyproject_path)
    requirements_items = parse_requirements(requirements_path)
    req_alignment = requirements_alignment(dependencies, requirements_items)

    readme_text = readme_path.read_text(encoding="utf-8") if readme_path.exists() else ""
    readme_marker_present = README_MARKER_START in readme_text and README_MARKER_END in readme_text
    readme_references_requirements = "requirements.txt" in readme_text
    readme_references_pyproject = "pyproject.toml" in readme_text

    launcher_records: list[dict[str, Any]] = []
    for rel_path in LAUNCHER_CANDIDATES:
        path = repo_root / rel_path
        if not path.exists() or not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        references_requirements = "requirements.txt" in text
        uses_python_m_pip = "python -m pip install -r requirements.txt" in text
        launcher_records.append(
            {
                "path": rel_path,
                "references_requirements_txt": references_requirements,
                "uses_python_m_pip_requirements_install": uses_python_m_pip,
                "install_contract_marker_present": "4B436637B install contract" in text,
                "aligned": (not references_requirements) or uses_python_m_pip,
            }
        )

    launcher_aligned_count = sum(1 for item in launcher_records if item["aligned"] is True)
    launcher_misaligned_count = len(launcher_records) - launcher_aligned_count
    install_contract_complete = (
        pyproject_path.exists()
        and len(dependencies) > 0
        and requirements_path.exists()
        and bool(req_alignment["requirements_pyproject_aligned"])
        and ((not readme_path.exists()) or readme_marker_present)
        and launcher_misaligned_count == 0
    )

    payload: dict[str, Any] = {
        "contract_name": "install_contract_alignment",
        "install_contract_alignment_complete": install_contract_complete,
        "install_contract_alignment_locked": install_contract_complete,
        "install_contract_alignment_status": "INSTALL_CONTRACT_ALIGNMENT_READY" if install_contract_complete else "INSTALL_CONTRACT_ALIGNMENT_NOT_READY",
        "install_contract_alignment_gap_id": "P0_INSTALL_CONTRACT_ALIGNMENT",
        "install_contract_alignment_mutation_allowed_scope": ["requirements.txt", "README.md", "launcher_install_command_comments"],
        "install_contract_destructive_mutation_allowed": False,
        "pyproject_exists": pyproject_path.exists(),
        "pyproject_path": "pyproject.toml",
        "pyproject_dependency_count": len(dependencies),
        "pyproject_dependencies_digest": stable_digest(list(dependencies)) if dependencies else None,
        "requirements_exists": requirements_path.exists(),
        "requirements_path": "requirements.txt",
        "requirements_expected_digest": expected_requirements_digest(dependencies) if dependencies else None,
        "requirements_actual_digest": hashlib.sha256(requirements_path.read_bytes()).hexdigest() if requirements_path.exists() else None,
        "requirements_contract_generated_by_37b": requirements_path.exists() and REQUIREMENTS_HEADER.strip() in requirements_path.read_text(encoding="utf-8"),
        "readme_exists": readme_path.exists(),
        "readme_contract_marker_present": readme_marker_present,
        "readme_references_requirements_txt": readme_references_requirements,
        "readme_references_pyproject_toml": readme_references_pyproject,
        "launcher_candidate_count": len(launcher_records),
        "launcher_aligned_count": launcher_aligned_count,
        "launcher_misaligned_count": launcher_misaligned_count,
        "launcher_records": launcher_records,
        "install_contract_mutation_performed": False,
        "file_delete_performed": False,
        "file_move_performed": False,
        "destructive_cleanup_performed": False,
    }
    payload.update(req_alignment)
    payload["install_contract_alignment_digest"] = stable_digest(payload)
    return payload


def build_p0_gap_closure_delta(install_contract: Mapping[str, Any]) -> dict[str, Any]:
    closed_items = [dict(item) for item in P0_GAPS_AFTER_37B]
    if not install_contract.get("install_contract_alignment_complete"):
        closed_items[0]["closed"] = False
        closed_items[0]["closed_by"] = None
    closed_count = sum(1 for item in closed_items if item.get("closed") is True)
    payload: dict[str, Any] = {
        "delta_name": "p0_gap_closure_delta",
        "p0_gap_closure_delta_complete": bool(install_contract.get("install_contract_alignment_complete")),
        "p0_gap_closure_delta_locked": bool(install_contract.get("install_contract_alignment_complete")),
        "p0_gap_closure_delta_status": "P0_1_INSTALL_CONTRACT_GAP_CLOSED" if install_contract.get("install_contract_alignment_complete") else "P0_1_INSTALL_CONTRACT_GAP_NOT_CLOSED",
        "p0_hardening_gap_count_after_37b": len(closed_items),
        "p0_hardening_closed_gap_count_after_37b": closed_count,
        "p0_hardening_open_gap_count_after_37b": len(closed_items) - closed_count,
        "p0_install_contract_alignment_closed": bool(install_contract.get("install_contract_alignment_complete")),
        "p0_install_contract_alignment_closed_by": PATCH_VERSION if install_contract.get("install_contract_alignment_complete") else None,
        "p0_hardening_complete": False,
        "p0_hardening_performed": True if install_contract.get("install_contract_alignment_complete") else False,
        "p0_hardening_auto_close_allowed": False,
        "p0_gap_closure_items": closed_items,
    }
    payload["p0_gap_closure_delta_digest"] = stable_digest(payload)
    return payload


def build_no_submit_p0_1_hardening_gate(install_contract: Mapping[str, Any], delta: Mapping[str, Any]) -> dict[str, Any]:
    gate_checks = [
        {"check_id": "source_37a_ready", "ready": True, "unlock_allowed": False},
        {"check_id": "install_contract_aligned", "ready": bool(install_contract.get("install_contract_alignment_complete")), "unlock_allowed": False},
        {"check_id": "requirements_pyproject_aligned", "ready": bool(install_contract.get("requirements_pyproject_aligned")), "unlock_allowed": False},
        {"check_id": "readme_contract_marker_present_or_not_applicable", "ready": bool((not install_contract.get("readme_exists")) or install_contract.get("readme_contract_marker_present")), "unlock_allowed": False},
        {"check_id": "launcher_contract_aligned", "ready": int(install_contract.get("launcher_misaligned_count", 0)) == 0, "unlock_allowed": False},
        {"check_id": "p0_1_closed_only", "ready": int(delta.get("p0_hardening_closed_gap_count_after_37b", 0)) == 1, "unlock_allowed": False},
        {"check_id": "paper_transition_remains_blocked", "ready": True, "unlock_allowed": False},
        {"check_id": "network_submit_forbidden", "ready": True, "unlock_allowed": False},
        {"check_id": "next_phase_not_auto_unlocked", "ready": True, "unlock_allowed": False},
    ]
    ready_count = sum(1 for item in gate_checks if item["ready"] is True)
    payload: dict[str, Any] = {
        "gate_name": "no_submit_p0_1_hardening_gate",
        "no_submit_p0_1_hardening_gate_complete": ready_count == len(gate_checks),
        "no_submit_p0_1_hardening_gate_locked": ready_count == len(gate_checks),
        "no_submit_p0_1_hardening_gate_status": "NO_SUBMIT_P0_1_HARDENING_GATE_READY" if ready_count == len(gate_checks) else "NO_SUBMIT_P0_1_HARDENING_GATE_NOT_READY",
        "no_submit_p0_1_hardening_gate_check_count": len(gate_checks),
        "no_submit_p0_1_hardening_gate_ready_count": ready_count,
        "no_submit_p0_1_hardening_gate_checks": gate_checks,
        "next_phase_unlock_allowed": False,
        "next_phase_unlock_performed": False,
        "transition_to_next_phase_allowed": False,
        "transition_to_next_phase_performed": False,
        "paper_transition_blocked": True,
        "paper_transition_ready": False,
        "paper_transition_unblocked": False,
    }
    payload["no_submit_p0_1_hardening_gate_digest"] = stable_digest(payload)
    return payload


def _source_37a_missing_payload() -> dict[str, Any]:
    return {
        "source_37a_complete": False,
        "source_37a_status": "SOURCE_37A_NOT_READY",
        "source_37a_safety_violation_count": 0,
        "source_37a_safety_violations": [],
        "source_37a_report": None,
    }


def evaluate_install_contract_alignment(repo_root: Path, reports_dir: Path, *, write_reports: bool = False) -> dict[str, Any]:
    repo_root = repo_root.resolve()
    reports_dir = reports_dir.resolve()
    errors: list[str] = []
    source_path = latest_report(reports_dir, SOURCE_37A_PATTERN)
    source_37a: dict[str, Any] = {}
    if source_path is None:
        errors.append(f"missing_source_37a_report:{SOURCE_37A_PATTERN}")
    else:
        try:
            source_37a = load_json(source_path)
        except Exception as exc:  # pragma: no cover
            errors.append(f"invalid_source_37a_report:{source_path}:{exc}")

    source_safety_violations = truthy_violations(source_37a, NO_SUBMIT_FALSE_FLAGS) if source_37a else []
    source_37a_complete = (
        bool(source_37a)
        and source_37a.get("status") == "READY"
        and source_37a.get("decision") == "POST_PHASE_36_PRODUCTION_READINESS_REBASELINE_READY_NO_SUBMIT_37A_PLANNING_GATE_LOCKED"
        and source_37a.get("source_36g_complete") is True
        and source_37a.get("phase_36_final_closed") is True
        and source_37a.get("phase_37_planning_only") is True
        and source_37a.get("phase_37_unlocked") is False
        and source_37a.get("production_readiness_rebaseline_ready") is True
        and source_37a.get("p0_hardening_gap_matrix_complete") is True
        and int(source_37a.get("p0_hardening_open_gap_count", 0)) >= 10
        and len(source_safety_violations) == 0
    )

    git_state = read_git_state(repo_root)
    install_contract = audit_install_contract(repo_root)
    p0_delta = build_p0_gap_closure_delta(install_contract)
    gate = build_no_submit_p0_1_hardening_gate(install_contract, p0_delta)

    ready = (
        source_37a_complete
        and bool(install_contract.get("install_contract_alignment_complete"))
        and bool(p0_delta.get("p0_gap_closure_delta_complete"))
        and bool(gate.get("no_submit_p0_1_hardening_gate_complete"))
        and not errors
    )
    status = "READY" if ready else "NOT_READY"
    decision = READY_DECISION if ready else NOT_READY_DECISION
    stamp = utc_stamp()

    result: dict[str, Any] = {
        "ok": ready,
        "status": status,
        "decision": decision,
        "errors": errors,
        "patch_id": PATCH_ID,
        "patch_name": PATCH_NAME,
        "patch_version": PATCH_VERSION,
        "check_name": CHECK_NAME,
        "git_available": git_state.git_available,
        "git_branch": git_state.git_branch,
        "git_head_short": git_state.git_head_short,
        "phase_37_tags_observed": list(git_state.local_phase_37_tags),
        "phase_37_tag_count_observed": len(git_state.local_phase_37_tags),
        "source_37a_complete": source_37a_complete,
        "source_37a_status": "SOURCE_37A_READY" if source_37a_complete else "SOURCE_37A_NOT_READY",
        "source_37a_report": str(source_path) if source_path else None,
        "source_37a_decision": source_37a.get("decision"),
        "source_37a_safety_violation_count": len(source_safety_violations),
        "source_37a_safety_violations": source_safety_violations,
        "source_37a_phase_36_final_closed": source_37a.get("phase_36_final_closed"),
        "source_37a_phase_37_planning_only": source_37a.get("phase_37_planning_only"),
        "source_37a_p0_open_gap_count": source_37a.get("p0_hardening_open_gap_count"),
        "phase_34_closed": True,
        "phase_35_closed": True,
        "phase_36_final_closed": bool(source_37a.get("phase_36_final_closed", False)) if source_37a else False,
        "phase_37_planning_only": True,
        "phase_37_unlocked": False,
        "phase_37_execution_started": False,
        "production_hardening_p0_1_ready": ready,
        "production_hardening_p0_1_scope": "install_contract_alignment_only",
        "production_readiness_status": "P0_1_INSTALL_CONTRACT_ALIGNMENT_READY_NO_SUBMIT" if ready else "P0_1_INSTALL_CONTRACT_ALIGNMENT_NOT_READY_NO_SUBMIT",
        "paper_transition_status": "PAPER_TRANSITION_BLOCKED_37B_INSTALL_CONTRACT_ALIGNMENT_NO_SUBMIT",
        "next_phase": NEXT_PHASE,
        "accepted_for_install_contract_alignment": ready,
        "install_contract_alignment_path": None,
        "p0_gap_closure_delta_path": None,
        "no_submit_p0_1_hardening_gate_path": None,
        "report_path": None,
    }
    result.update(install_contract)
    result.update(p0_delta)
    result.update(gate)

    for flag in NO_SUBMIT_FALSE_FLAGS:
        result[flag] = False
    result["paper_transition_blocked"] = True
    result["paper_transition_ready"] = False
    result["paper_transition_unblocked"] = False
    result["paper_transition_approval_performed"] = False
    result["paper_environment_enabled"] = False
    result["live_environment_enabled"] = False
    result["network_request_allowed_now"] = False
    result["exchange_submit_allowed"] = False
    result["network_submit_allowed"] = False
    result["paper_submit_allowed"] = False
    result["live_real_submit_allowed"] = False
    result["runtime_overlay_allowed"] = False
    result["order_submit_performed"] = False
    result["exchange_submit_performed"] = False
    result["trading_action_performed"] = False
    result["training_performed"] = False
    result["reload_performed"] = False
    result["runtime_overlay_activated"] = False
    result["install_contract_mutation_performed"] = False
    result["requirements_alignment_mutation_performed"] = False
    result["readme_install_contract_mutation_performed"] = False
    result["launcher_install_contract_mutation_performed"] = False

    if write_reports:
        reports_dir.mkdir(parents=True, exist_ok=True)
        install_path = reports_dir / f"{PATCH_ID}_install_contract_alignment_{stamp}.json"
        delta_path = reports_dir / f"{PATCH_ID}_p0_gap_closure_delta_{stamp}.json"
        gate_path = reports_dir / f"{PATCH_ID}_no_submit_p0_1_hardening_gate_{stamp}.json"
        report_path = reports_dir / f"{PATCH_ID}_install_contract_alignment_{stamp}_{status.lower()}.json"
        write_json(install_path, install_contract)
        write_json(delta_path, p0_delta)
        write_json(gate_path, gate)
        result["install_contract_alignment_path"] = str(install_path)
        result["p0_gap_closure_delta_path"] = str(delta_path)
        result["no_submit_p0_1_hardening_gate_path"] = str(gate_path)
        result["report_path"] = str(report_path)
        write_json(report_path, result)
    return result


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=f"{PATCH_VERSION} {PATCH_NAME}")
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--reports-dir", default="reports/recovery")
    parser.add_argument("--once-json", action="store_true")
    parser.add_argument("--write-reports", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    result = evaluate_install_contract_alignment(
        repo_root=Path(args.repo_root),
        reports_dir=Path(args.reports_dir),
        write_reports=bool(args.write_reports),
    )
    print(json.dumps(result, ensure_ascii=False, sort_keys=True))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
